### ISSUE TITLE
Django 3 is broken

### ISSUE THREAD

**Issue by ricco386** [Bouke/django-user-sessions#100]
Django 3 support is broken.

In Django 3: https://docs.djangoproject.com/en/3.0/releases/3.0/ there has been a backwards incompatible that from `django.utils.http` function `cookie_date` was removed. Therefore projects using this app are unable to upgrade to Django 3.

There is an easy fix to replace `cookie_date` with `http_date` which is in the same file.

**Comment by ricco386** [comment]
There are already 3 pull requests to fix this problem: #90, #97 and #99

**Comment by Bouke** [comment]
Merged #90, but thanks anyway.
