### ISSUE TITLE
Issue with django.contrib.messages session/middleware

### ISSUE THREAD

**Issue by johnfraney** [Bouke/django-user-sessions#25]
Hello! First of all, this app is nifty. I am having some issues getting it to play nicely with `django.contrib.messages`. Messages aren't being passed to my templates when I'm using this app instead of Django's default session engine/middleware.

I believe the issue centres around `SESSION_ENGINE = 'user_sessions.backends.db'`. Say I want to pass a message to my view:

```python
class Index(ListView):
    ...
    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        messages.info(self.request, 'Why, hello!')
        return context
```

I can access the message via `messages.get_messages()`, but the message doesn't appear in my template:

```htmldjango
...
{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
...
```

**Comment by Bouke** [comment]
Let me know if you have additional information to share.
