### ISSUE TITLE
Can't run clearsessions command

### ISSUE THREAD

**Issue by Gwildor** [Bouke/django-user-sessions#32]
Because the `clearsessions` management command is part of `django.contrib.sessions`, this command can't be run anymore. This is of course because that app has to be replaced  by `user_sessions`, and thus the command isn't loaded anymore.

**Comment by Bouke** [comment]
Thanks for the bug report! I think that a similar command should be provided by this package as well. Maybe a smart import could do the trick.

**Comment by Bouke** [comment]
Added this command in 337da8df. Will ship in next version.

**Comment by Bouke** [comment]
Released in version 1.2.0.
