### ISSUE TITLE
Using user-sessions in appengine 

### ISSUE THREAD

**Issue by abithyzis** [Bouke/django-user-sessions#37]
Hi,

I don't think it is a bug per se but user-sessions does not work in appengine 

The problem is caused by using `django.contrib.gis.geoip` here:
django-user-sessions/user_sessions/templatetags/user_sessions.py

and you can read about the problem and a solution in this SO question
http://stackoverflow.com/questions/4601684/using-geoip-with-django-on-appengine

I can do a pull request with the suggested solution.

Thank you

**Comment by Bouke** [comment]
`pygeoip` looks like a nice package to support besides the MaxMind C libraries. However, it's strange that there is no mention of `pygeoip` on the [Django issue list](https://code.djangoproject.com/search?q=pygeoip).

**Comment by abithyzis** [comment]
Following on that have you considered moving to geoip2?

**Comment by Bouke** [comment]
I have not, as I'm relying on the GeoIP features provided by Django. Following on that, I think it is trivial to implement a custom templatetag to use with any geo-provider, besides what is currently provided. I'm closing this ticket for now.
