### ISSUE TITLE
Warning django 1.9

### ISSUE THREAD

**Issue by GuillaumeCisco** [Bouke/django-user-sessions#38]
Not sure if I'm doing something incorrectly, but the installation tutorial says
In INSTALLED_APPS replace 'django.contrib.sessions' with 'user_sessions'.

If we do this, we end up with a deprecation warning:
```
/lib/python2.7/site-packages/django/contrib/sessions/models.py:27: RemovedInDjango19Warning: Model class django.contrib.sessions.models.Session doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class Session(models.Model):
```

But we also end up with a django_session table in the database if we keep 'django.contrib.sessions' alongside to 'user_sessions'.

**Comment by Bouke** [comment]
Django 1.9 is a development release, which is currently not supported. Once Django 1.9 matures support will be added in this package. Feel free to submit a pull request to resolve this issue, otherwise stick with 1.8.

**Comment by steve918** [comment]
This warning is present in 1.8, the only workaround I've found is if you don't comment out     'django.contrib.sessions' under INSTALLED_APPS and just put user_sessions underneath it and things still work as expected, but I'm not sure yet what side-effects that might have.

**Comment by GuillaumeCisco** [comment]
As written above, you'll have a sql table created.

**Comment by moreati** [comment]
This warning is triggered because `user_sessions.models` imports `django.contrib.sessions.models.SessionManager` which is in the same module as `d.c.s.models.Session`. However, even if SessionManager was in another module, it uses `d.c.s.db.SessionStore`, which also imports `d.c.s.models.Session`.

The only way I could find to avoid this, is to copy/paste `SessionManager` into `user_serssions.models`, but that
 1. introduces code duplication
 1. introduces a need to do a database migration

```diff
diff --git a/user_sessions/models.py b/user_sessions/models.py
index 1f646d1..eab6dfe 100644
--- a/user_sessions/models.py
+++ b/user_sessions/models.py
@@ -1,10 +1,27 @@
 import django
 from django.conf import settings
-from django.contrib.sessions.models import SessionManager
 from django.db import models
 from django.utils.translation import ugettext_lazy as _
 
 
+class SessionManager(models.Manager):
+    use_in_migrations = True
+
+    def encode(self, session_dict):
+        """
+        Returns the given session dictionary serialized and encoded as a string.
+        """
+        return SessionStore().encode(session_dict)
+
+    def save(self, session_key, session_dict, expire_date):
+        s = self.model(session_key, self.encode(session_dict), expire_date)
+        if session_dict:
+            s.save()
+        else:
+            s.delete()  # Clear sessions with no data.
+        return s
+
+
 class Session(models.Model):
     """
     Session objects containing user session information.
```

**Comment by nickfishman** [comment]
Django 1.9 was recently released, and the above warning is now a hard error that prevents the application from starting. It would be helpful to fix this.

**Comment by nickfishman** [comment]
I've started making some other fixes for Django 1.9 in a fork: https://github.com/Bouke/django-user-sessions/pull/48. It's still a work in progress though.

**Comment by Bouke** [comment]
Thanks everyone, I've merged #40 and pushed additional fixes as well; available in master.

**Comment by GuillaumeCisco** [comment]
Thank you everyone, will this code be available as 1.3 tag?

**Comment by Bouke** [comment]
Seeing that there are some backwards incompatible changes, it'll probably be released as a minor release (1.3 is up next).

**Comment by GuillaumeCisco** [comment]
Sorry for asking again.
Should we use the master branch version for our requirements files or a specific tag will be added?
1.2.1 tag?

**Comment by Bouke** [comment]
That's entirely up to you; the master branch is under development, your mileage might vary.
