### ISSUE TITLE
Session queryset only showing currently logged in user

### ISSUE THREAD

**Issue by mhb11** [Bouke/django-user-sessions#45]
@Bouke  : I'm trying to use django-user-sessions to get all users who have had a session on my website within the last 5 mins. Since it's a social website, it's quite relevant for my users to see who else has recently been online. 

For the said purpose, I wrote:
`recent_users = Session.objects.filter(last_activity__gte=(timezone.now()-timedelta(minutes=500))).only('user').distinct('user')`

But when I test this in localhost, it only returns the **currently logged in user** in `recent_users`. Does the "Session" model only maintain sessions that *currently exist*?

**Comment by Bouke** [comment]
If a users chooses to logout, the session will be removed from the database, as seen here:  https://github.com/Bouke/django-user-sessions/blob/b7d4b8ddf4555268535627a1588790435cab94f2/user_sessions/backends/db.py#L102. Inactive sessions might be removed after a while by running the respective management command.
