### ISSUE TITLE
TypeError: __init__() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by bhaskar8088** [Bouke/django-user-sessions#46]
python2.7/site-packages/filebrowser_safe/decorators.py", line 21, in decorator
    session_data = engine.SessionStore(request.POST.get('session_key'))

As per the above log, filebrowser_safe is using SessionStore. Any idea on the best way to fix this ?

Link to filebrowser_safe page - https://github.com/stephenmcd/filebrowser-safe/blob/master/filebrowser_safe/decorators.py

**Comment by Bouke** [comment]
That code assumes that the `SessionStore` can be initialized with only a session key, however the backend provided by this package requires more, as provided by the middleware. To me it looks like "filebrowser_safe" should use another way of identifying the user, or provide the additional (non-standard) parameters.
