### ISSUE TITLE
Relation "user_sessions_session" does not exist

### ISSUE THREAD

**Issue by mhb11** [Bouke/django-user-sessions#50]
Hello,

I recently moved my Django application with Postgres back-end to Azure from Heroku. This app uses your *user_sessions* library instead of django.contrib.sessions. The chief use of user_sessions is to show, to every user on my Django app, what other usernames had a session within the same app in the last 5 mins. It's basically a 'who-else-is-online' feature.

I took a snapshot of my live Heroku app's data via pg_dump. I next tried to restore this snapshot on my new server on Azure. All went smoothly. Finally, when I tried to access my app via example.cloudapp.net, I got the error below, pointing to user_sessions. I have searched far and wide, but still don't understand what's going on. Do you happen to know what could be the problem here? I have checked in psql, user_sessions_session does exist, and contains data.

>Exception Type: 	DatabaseError
>Exception Value: 	
>
>relation "user_sessions_session" does not exist
>LINE 1: ...last_activity", "user_sessions_session"."ip" FROM "user_sess...
 >                                                            ^
>
>Exception Location: 	/home/mhb11/.virtualenvs/redditpk/local/lib/python2.7/site-packages/django>/db/backends/postgresql_psycopg2/base.py in execute, line 54

Happy holidays.

**Comment by Bouke** [comment]
I'm not sure I can help you with this. It seems related to some database issue, you'd better ask this over at StackOverflow.

**Comment by mhb11** [comment]
Sure, no problem. I thought I'd run it by you in case it was something related you could spot. Thanks.
