### ISSUE TITLE
Django's GeoIP deprecation in favour of GeoIP2

### ISSUE THREAD

**Issue by alexbarcelo** [Bouke/django-user-sessions#51]
I was just on the pre-flight check of requirements for django-user-sessions, and GeoIP [has been just deprecated in Django 1.9](https://docs.djangoproject.com/en/1.9/ref/contrib/gis/geoip/), in favour of [GeoIP2](https://docs.djangoproject.com/en/1.9/ref/contrib/gis/geoip2/). 

There is a closed issue #37 which mentions GeoIP2, but this was when Django didn't support it (pre-1.9). I don't know if this really changes anything. Because GeoIP2 is new for Django 1.9, and the same Django 1.9 starts to deprecate the previous version, which is a bit sudden. Do you have any thoughts about that?

[I have no strong feelings one way or the other, simply wanted to check before designing my production environment]

**Comment by Bouke** [comment]
Looks interesting to check out. However as Django 1.8 has extended support until at least april 2018, there would need to be support for the deprecated GeoIP as well.

**Comment by Bouke** [comment]
Django 2.0 [will drop GeoIP][0], so there will be some time remaining for transitioning. However as GeoIP doesn't support IPv6 it might be worthwhile to support both API's in the interim. Regarding Django 1.8, support for that version could be dropped sooner. So I guess I'm open to replace GeoIP with GeoIP2.

[0]: https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-2-0

**Comment by Bouke** [comment]
Resolved in 043dce969fd0c4496287fd1cffcdcc73dc58fce6.
