### ISSUE TITLE
Optimizing sessions

### ISSUE THREAD

**Issue by mhb11** [Bouke/django-user-sessions#52]
Hello, 

With Django's built-in sessions, I can do the following for perf. optimization:
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
OR
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

Is there anything similar with user_sessions?

**Comment by Bouke** [comment]
There's no such feature available.

**Comment by mjnaderi** [comment]
We have implemented a customized `cached_db` backend for this purpose. Sessions have a foreign key to User and store user agent and IP:

https://github.com/QueraTeam/django-qsessions
