### ISSUE TITLE
Setting SESSION_COOKIE_HTTPONLY

### ISSUE THREAD

**Issue by mhb11** [Bouke/django-user-sessions#53]
@Bouke I've been using this plugin. Do I separately need to set SESSION_COOKIE_HTTPONLY=True in settings.py (or something equivalent)? Please advise

My session cookies do not currently have the HttpOnly flag set which makes it susceptible to manipulation via client-side code such as JavaScript. When combined with other vulnerabilities such as XSS this allows attackers to steal a customer's active session, allowing them to masquerade as the customer.

**Comment by Bouke** [comment]
This package's `SessionMiddleware` middleware –which sets the cookie– is based on Django's original `SessionMiddleware`. So it should work like [explained in the Django documentation][1]:

> SESSION_COOKIE_HTTPONLY
>
> Default: True
> 
> Whether to use HTTPOnly flag on the session cookie. If this is set to True, client-side JavaScript will not to be able to access the session cookie.
> 
> HTTPOnly is a flag included in a Set-Cookie HTTP response header. It is not part of the RFC 2109 standard for cookies, and it isn’t honored consistently by all browsers. However, when it is honored, it can be a useful way to mitigate the risk of client side script accessing the protected cookie data.
> 
> Turning it on makes it less trivial for an attacker to escalate a cross-site scripting vulnerability into full hijacking of a user’s session. There’s not much excuse for leaving this off, either: if your code depends on reading session cookies from JavaScript, you’re probably doing it wrong.

[1]: https://docs.djangoproject.com/en/1.9/ref/settings/#session-cookie-httponly
