### ISSUE TITLE
Speeding up session ORM queries via introducing redis

### ISSUE THREAD

**Issue by mhb11** [Bouke/django-user-sessions#58]
Hey there,

I'm using this excellent library of yours to track who all visited my website in the last 5 mins. I subsequently show users a "who's online" section built via this functionality. The query ends up being:

`Session.objects.filter(last_activity__gte=(timezone.now() - timedelta(minutes=5))).only('user').distinct('user').prefetch_related('user__userprofile')`

As the activity on my website has recently exploded, this "who's online" feature has really become slow. In the bid to get back some performance, I'm thinking of introducing redis into the mix. Now in `backends/db.py`, the `save` function creates the session object. All I need to do is this: when a session obj is being created, save the relevant `self.user_id` and a `timestamp` in a redis powered key-value store (a `sorted set` to be precise). This way, I can replace the slow Django query above with a faster one that gets recent online user_ids from redis. 

I was about to override the `save` function in this way, but being a newbie, I don't want to break anything in my app. So I thought I'd run this strategy by you first. Any problems in what I've written here? Any thing you'd want me to look for when I do this? Thanks in advance!

Thanks in advance!

**Comment by Bouke** [comment]
Thanks! Could you share some metrics about that query? Maybe there's some additional models that are being pulled in? I've always had great help from django-debug-toolbar. It doesn't feel right that a query like that brings down your site. Nevertheless, you might be able to override some methods to save to redis.

--
Bouke
