### ISSUE TITLE
Error trying close a session in Firefox from other session in Chrome

### ISSUE THREAD

**Issue by apphillipe** [Bouke/django-user-sessions#60]
I have a Django's middleware controlling when a user try logging in and exists another user logged with the same. My code checks if exist one more user logged and shows a template asking if the user want logout or finish the others sessions. If the user choses finish the other session, he is redirected to system. The request.path is useful to accept the requests only login and session/delete views.

    def process_request(self, request):
        try:
             object_list = request.user.session_set.filter(expire_date__gt=timezone.now())
        except:
             object_list = None

        if object_list and len(object_list) > 1:
            if request.path != '/users/session/delete' and request.path != '/login/':
                 return logout(request)

         return None

The error happens when from Chrome I try finish one session running on Firefox. It redirects to logout instead logging in the system. When I test the feature in localhost, it performs normally. Looking for the error I found that the 'referer' in request header is different when I use localhost and web from Chrome.

**Comment by Bouke** [comment]
Interesting use-case of the library :). I don't really know what's going on here. It could be that Chrome is performing other requests in the background. Like fetching a favicon, which might not exist, so it hits Django's 404 page, which in turn isn't whitelisted in your middleware, thus triggering the logout. But be something else entirely; you could find out by doing additional logging from your middleware.

The issues section here on GitHub is not a good place for your question though, it might be better to ask this on StackOverflow.

**Comment by apphillipe** [comment]
Thank you for your help, Boke. My apologies for posting the error as issue. I also asked on stackoverflow and I'm without answers yet. I made a change in code, using a session variable instead of get the url, which also did not work. I'm investigating the idea of the favicon, it seems this is what is happening. Thanks one more time.
