### ISSUE TITLE
Preventing session data loss when changing session backend

### ISSUE THREAD

**Issue by mhb11** [Bouke/django-user-sessions#61]
I was reverting from user-sessions back to Django's own `django.contrib.sessions`. Upon changing my settings.py, I get a Database error (`relation django_session does not exist`). Do I need to run migrations again? And would I definitely lose all session data? I want to avoid that.  

Btw FYI, I changed MIDDLEWARE_CLASSES, INSTALLED_APPS and the SESSION ENGINE in settings.py when

**Comment by Bouke** [comment]
You should be able to migrate the sessions between both backends. The models have a very similar structure, allowing you to migrate data between database tables.
