### ISSUE TITLE
Maintaining user sessions between subdomains

### ISSUE THREAD

**Issue by mhb11** [Bouke/django-user-sessions#68]
I'm using your excellent library in a Django project I maintain. Currently, one behavior is that session information is not maintained for the same user between `example.com` and `www.example.com`. Researching this issue has [led](http://stackoverflow.com/questions/2116860/django-session-cookie-domain-with-multiple-domains) me to believe that I need to add the following in my settings.py:

`SESSION_COOKIE_DOMAIN=".example.com"` 

Since I'm not relying on `django.contrib.session` or `django.contrib.sessions.middleware.SessionMiddleware` in my app, I felt I'd run this by you, in case there are unforeseen issues in using the above setting. Related SO question is [here](http://stackoverflow.com/questions/41809613/user-session-discrepancy-across-subdomains-pointing-to-the-same-dns-name).

**Comment by Bouke** [comment]
Should work fine I guess. This package doesn't do anything besides adding a few fields on the session, so should work similar to Django's normal session middleware.
