### ISSUE TITLE
Improve Documentation for GeoIP2 Support

### ISSUE THREAD

**Issue by idflores** [Bouke/django-user-sessions#76]
The link in the `README.md` file for GeoIP is *404*.  The new link is:

[https://docs.djangoproject.com/en/1.11/ref/contrib/gis/geoip/](https://docs.djangoproject.com/en/1.11/ref/contrib/gis/geoip/)

Since GeoIP is deprecated since Django v1.9, does this app support [GeoIP2](https://docs.djangoproject.com/en/1.11/ref/contrib/gis/geoip2/)?

In addition, both GeoIP and GeoIP2 seem to be supported by Django "out-of-the-box" in Django v1.11 using the libraries `django.contrib.gis.geoip` and `django.contrib.gis.geoip2` respectively. Is there a need to worry about installation of the GeoIP libraries anymore?

![django user_sessions issue](https://user-images.githubusercontent.com/12431665/26891865-1de1cbde-4b7c-11e7-8487-5ea6940a1a09.png)

Perhaps we could update the `README.md` with these details for clarity?

**Comment by Bouke** [comment]
There is support, see 93f0a524bf8ec7992a6cf351b631212b25c1e393. Documentation could be improved, I'll leave this ticket open to track the progress.

**Comment by idflores** [comment]
AH! Thanks for the commit reference @Bouke ! I tried looking through the code earlier before asking...

**Comment by Bouke** [comment]
#78 adds instructions for GeoIP to the readme.

**Comment by Bouke** [comment]
2bd55f5 adds instructions for GeoIP2 to the documentation
