### ISSUE TITLE
Location template tag and missing city binary

### ISSUE THREAD

**Issue by abithyzis** [Bouke/django-user-sessions#79]
When only the country binary is included in the project the `geoip().city` throws an exception. In the code I see that there is a fallback to display the country name only when city is missing, so I wondering if this could be extended to also take into account a missing binary.

**Comment by Bouke** [comment]
Can you give an easy example how this problem can be replicated? Are you getting an exception somewhere? If so, under what conditions?

**Comment by abithyzis** [comment]
Of the two files mentioned in GeoIP2 `GeoLite2-Country.mmdb` and `GeoLite2-City.mmdb` I *can* only use the Country file. When the city file is missing [geoip().city(value)](https://github.com/Bouke/django-user-sessions/blob/master/user_sessions/templatetags/user_sessions.py#L100) throws an exception.
As a side note, shouldn't `location['country_name']` be `'country_name' in location`

**Comment by Bouke** [comment]
I've resolved this issue in 1dc445c5996dc172d6b2f260accd5492a73c39fd and released it with 1.5.2. Please let me know if this fixes the issue for you.
