### ISSUE TITLE
not displyed other user session info when acessss to  account/sessions

### ISSUE THREAD

**Issue by sinjorjob** [Bouke/django-user-sessions#84]
I am a begginer of django from japan.
When access to url account/sessions, only the accessing  user session infomation are displayed,
(other user session info are not displayed.)
But, when access to admin site, all user information are displayed.
Is this a bug? or specification?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Browser and version: IE11, google Chrome,
* Python version: 3.6.3
* Django version: 2.0
* django-otp version:
* django-user-sessions version:latest ver
* Link to your project:

**Comment by Bouke** [comment]
This is how it is designed. The default views only allow you to see your own sessions.
